// news.js
export const TOGGLESHOWTYPES = 'TOGGLESHOWTYPES'
export const ADDNEWS = 'ADDNEWS'
export const CHANGENEXTCOLUNMS = 'CHANGENEXTCOLUNMS'
export const CHANGENOWTYPE = 'CHANGENOWTYPE'
export const RESETLATESTPAGE = 'RESETLATESTPAGE'
export const CLEARNEWS = 'CLEARNEWS'
export const CLEARNEXTCOLUNMS = 'CLEARNEXTCOLUNMS'
// user.js
export const CHANGEMODALSTATE = 'CHANGEUSERSTATE'
export const TOGGLEMODLA = 'TOGGLEMODLA'
export const TOGGLELOGIN = 'TOGGLELOGIN'
export const TOGGLEISUSERMENU = 'TOGGLEISUSERMENU'
export const CHANGEUSERNAME = 'CHANGEUSERNAME'
