// news.js
export const ADDNEWS = 'ADDNEWS'
export const CHANGENEXTCOLUNMS = 'CHANGENEXTCOLUNMS'
// user.js
export const CHANGEMODALSTATE = 'CHANGEUSERSTATE'
export const TOGGLEMODLA = 'TOGGLEMODLA'
export const TOGGLELOGIN = 'TOGGLELOGIN'
